### ISSUE TITLE
migrate ocp4

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/automation#58]
ODF VMes from storm3:
compute0: pci_0000_81_00_0 on storm3
compute1: pci_0000_83_00_0 on storm3
compute2:  pci_0000_84_00_0 on storm3

### ToDo's 

- [x] ⚪ Cleanup the cluster - remove old not used workload (boby car for example?)
   - Removed old open-cluster-managedment
   - Several orphan workloads from Red Haters not at Red Hat anymore and more
   - Costmanagment operator deinstalled
   - Deleted orphan sunset/sunsetdb in openshift-operators
- [X] 🟢 Add NetApp Trident CSI NFS Storage driver for new store requests
- [ ] 🛠️  Migrate / Remove all ODF PVC to NetApp Storage
   - [X] 🟢 Cluster Monitoring
   - [x] 🟢 Internal Registry
   - [x] 🟢 User / Workload PVC - E-Mail to all Users - WiP: https://github.com/stormshift/automation/issues/58#issuecomment-2560254407
   - [X] 🟢 Remove ODF
- [x] 🟢 Remove managed-nfs-prov. NFS Server provided from support node
- [x] 🟢 Prepare a ocp4 network in COE LAb 172.16.10.0/24 (dgw: 172.16.10.1, dns: 172.16.10.5), VLAN ID: 1004 VLAN-NAme: stormshift-ocp4 
  - [x] 🟢  Prepare router VM - not needed already done by bastion
- [x] 🟢 Services at ocp4support vm: dhcpd, dns server, router 
- [x] 🟢 Create a VLAN Based network
- [x] 🟢 Shutdown all VM's change network into the vlan based network
- [x] 🟢 Add NetApp into the VLAN
- [x] 🟢  Migrate storage (PV/PVC) to NetApp (https://access.redhat.com/solutions/7089972)
- [X] 🟢   Run MTV to migration VM's from RHV to OpenShift-Virt into the same VLAN. Based case without any cluster downtime.
    - ⚠️ Difficult: During the migration, the chipset will change from `I440FX` to `q35`. The  result is the interface name changed from `ens2` to `enp1s0`. And network configuration gets lost because it's still at to the old interface. (https://issues.redhat.com/browse/MTV-1847)
- [X] 🟢 Rollout `/etc/udev/rules.d/70-persistent-net.rules` to persiste device after chipset change
   - [x] ocp4bastion
   - [x] ocp4support
   - [x] ocp4compute-0
   - [x] ocp4compute-1
   - [x] ocp4compute-2
   - [x] ocp4control-0
   - [x] ocp4control-1
   - [x] ocp4control-2 
- 🔴 AFTER ALL - Migrate VM's from RHV to OpenShift-Virt

/cc @Javatar81

**Comment by rbo** [comment]
Is there any hard requirement for ODF on that cluster?

**Comment by rbo** [comment]
ToDo's 

- [ ] Cleanup the cluster - remove old not used workload (boby car for example?)
- [ ] Add NetApp Trident CSI NFS Storage driver for new store requests
- [ ] Migrate / Remove all ODF PVC to NetApp Storage
- [ ] Remove managed-nfs-prov. NFS Server provided from support node
- [ ] Prepare a ocp4 network in COE LAb 172.16.10.0/24 (dgw: 172.16.10.1, dns: 172.16.10.5), VLAN ID: 1004 VLAN-NAme: stormshift-ocp4 
  - [ ] Prepare router VM

Services at ocp4support vm:
  * dhcpd
  * dns forwarder 

Idea: 
 - Create a VLAN Based network
 - Shutdown all VM's change network into the vlan based network
 - Add NetApp into the VLAN
 - Migrate storage (PV/PVC) to NetApp
 - Run MTV to migration VM's from RHV to OpenShift-Virt into the same VLAN. Based case without any cluster downtime.

/cc @Javatar81

**Comment by rbo** [comment]
### VLAN configuration
* [Documented](https://docs.google.com/spreadsheets/d/1iwXilV1V84IQN7mKOIHq28-9P5bWabN019TJPaJ_3Es/edit?gid=116822073#gid=116822073)

<details>
<summary>Switch configuration arista-sfp</summary>

```
arista-sfp>enable
arista-sfp#config
arista-sfp(config)#vlan 1004
arista-sfp(config-vlan-1004)#name stormshift-ocp4
arista-sfp(config-vlan-1004)#interface Et1-36
arista-sfp(config-if-Et1-4,6/1-36)#switchport trunk allowed vlan add 1004
arista-sfp(config-if-Et1-4,6/1-36)#interface Po11
arista-sfp(config-if-Po11)#switchport trunk allowed vlan add 1004
arista-sfp(config-if-Po11)#write
Copy completed successfully.
arista-sfp(config-if-Po11)#copy running-config startup-config
Copy completed successfully.
arista-sfp(config-if-Po11)#
```

</details>

<details>
<summary>Switch configuration arista-rj45</summary>

```
arista-rj45>enable
arista-rj45#config
arista-rj45(config)#vlan 1004
arista-rj45(config-vlan-1004)#name stormshift-ocp4
arista-rj45(config-vlan-1004)#interface Et1-Et48
arista-rj45(config-if-Et1-48)#switchport trunk allowed vlan add 1004
arista-rj45(config-if-Et1-48)#interface Po11
arista-rj45(config-if-Po11)#switchport trunk allowed vlan add 1004
arista-rj45(config-if-Po11)#write
Copy completed successfully.
arista-rj45(config-if-Po11)#copy running-config startup-config
Copy completed successfully.
arista-rj45(config-if-Po11)#
```

</details>

**Comment by rbo** [comment]
Created a test rhel 9.1 VM at RHEV and OCP-V VM's can comunicate and have access to NetApp. 

Tested MTV of test vm: Moved from RHV to OCP-V - problem: network interface name changed and lost of static IP config. Not good...  FI: ocp4 use dhcp.... not static IP.

**Comment by rbo** [comment]
https://issues.redhat.com/browse/MTV-1847

**Comment by rbo** [comment]
Tried to migrate ocp4support,
```
admission webhook "virtualmachine-validator.kubevirt.io" denied the request: failure checking preference requirements: insufficient Memory resources of 1Gi provided by VirtualMachine, preference requires 1536Mi
```
Memory Size: 1024 MB 

To test the migration changed the memory size to 2048.

**Comment by rbo** [comment]
### Moved VMs into VLAN 1004 ✅ 
* Shutdown cluster via https://examples.openshift.pub/cluster-lifecycle/shutdown/
* Changed network of all VM's
* Start up cluster again

**Comment by rbo** [comment]
### managed-nfs-prov removed ✅

**Comment by rbo** [comment]
### NetApp Trident configured ✅ 


```
Warning  Failed  81s (x17 over 6m58s)  trident-crd-controller  Failed to create backend: problem initializing storage driver 'ontap-san-economy': could not configure storage pools: could not get storage pools from array: SVM stormshift-ocp4 has no assigned aggregates
```

```
fas2552::> vserver show -fields aggr-list
vserver aggr-list
------- --------------
disco   fas2552_02_SAS
fas2552 -
fas2552-01
        -
fas2552-02
        -
main    fas2552_02_SAS
manual  -
stormshift-ocp4
        -
svm_trident
        fas2552_02_SAS
8 entries were displayed.

fas2552::> vserver add-aggregates -vserver stormshift-ocp4 -aggregates  fas2552_02_SAS

fas2552::> vserver show -fields aggr-list
vserver aggr-list
------- --------------
disco   fas2552_02_SAS
fas2552 -
fas2552-01
        -
fas2552-02
        -
main    fas2552_02_SAS
manual  -
stormshift-ocp4
        fas2552_02_SAS
svm_trident
        fas2552_02_SAS
8 entries were displayed.

fas2552::>
fas2552::>

```

**Comment by rbo** [comment]
We have to fix the multipath config:
```
sh-5.1# multipath -ll
0QEMU_QEMU_HARDDISK_1cb43761-2193-43d9-b6b9-5b6f164b5435 dm-1 QEMU,QEMU HARDDISK
size=10G features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  `- 0:0:0:0 sda     8:0   active ready running
nvme.8086-43564654353436313030333932503045474e-494e54454c205353445045444d443032305434-00000001 dm-0 NVME,INTEL SSDPEDMD020T4
size=1.8T features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  `- 0:0:1:1 nvme0n1 259:0 active ready running

```

Configuration right now:
```
defaults {
   user_friendly_names no
   find_multipaths no
   enable_foreign "^$"
}

blacklist_exceptions {
    property "(SCSI_IDENT_|ID_WWN)"
}

blacklist {
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^(td|ha)d[a-z]"
    device {
        vendor  "HP"
    }
    device {
        vendor  "Intel"
    }
    device {
        vendor  "HGST"
    }
}
```

**Comment by rbo** [comment]
#### Storage migration with MTC
Tried:
```
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    migration.openshift.io/selected-migplan-type: scc
  name: image-registry
  namespace: openshift-migration
spec:
  destMigClusterRef:
    name: host
    namespace: openshift-migration
  liveMigrate: false
  namespaces:
    - openshift-image-registry
  persistentVolumes:
    - capacity: 100Gi
      name: pvc-8059a107-3874-4ac3-b4a2-a747539fb712
      proposedCapacity: 100Gi
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: 'registry-storage-netapp-nas'
        namespace: openshift-image-registry
        volumeMode: Filesystem
      selection:
        action: copy
        copyMethod: filesystem
        storageClass: coe-netapp-nas
        verify: true
      storageClass: ocs-storagecluster-cephfs
      supported:
        actions:
          - skip
          - copy
        copyMethods:
          - filesystem
          - block
          - snapshot
  srcMigClusterRef:
    name: host
    namespace: openshift-migration
```

Works not too bad...

**Comment by rbo** [comment]
### Workload storage cleanup

@ortwinschneider @Javatar81 @maxisses Please migrate/delete your PVC at stormshift-ocp4 - new default storage class is coe-netapp-nas (NFS), block is also available via coe-netapp-san (iSCSI) -  the cleanup is mandatory for the migration away from RHEV! 

- [ ] admin-devspaces                                   	claim-devworkspace                                	ocs-storagecluster-cephfs
- [ ] bobbycar-hdpp                                     	vehicle-detection                                 	ocs-storagecluster-cephfs
- [ ] bobbycar                                          	data-volume-bobbycar-dg-0                         	ocs-storagecluster-cephfs
- [ ] bobbycar                                          	postgres-pvc                                      	ocs-storagecluster-cephfs
- [ ] bschmeli-devhub                                   	data-backstage-psql-developer-hub-0               	ocs-storagecluster-cephfs
- [ ] bschmeli-devhub                                   	data-developer-hub-postgresql-0                   	ocs-storagecluster-cephfs
- [ ] bschmeli-devjoy                                   	data-developer-hub-postgresql-0                   	ocs-storagecluster-cephfs
- [ ] bschmeli-redhat-com-devspaces-7t9v6h              	claim-devworkspace                                	ocs-storagecluster-cephfs
- [ ] costmanagement-metrics-operator                   	costmanagement-metrics-operator-data              	ocs-storagecluster-cephfs
- [ ] max-playing-around                                	max-workbench                                     	ocs-storagecluster-cephfs
- [ ] max-playing-around                                	notebookwithelyra                                 	ocs-storagecluster-cephfs
- [ ] mdargatz-redhat-com-devspaces-w20sig              	claim-devworkspace                                	ocs-storagecluster-cephfs
- [ ] openshift-operators                               	superset-data                                     	ocs-storagecluster-cephfs
- [ ] openshift-operators                               	supersetdb-data                                   	ocs-storagecluster-cephfs
- [ ] openshift-storage                                 	db-noobaa-db-0                                    	ocs-storagecluster-ceph-rbd
- [ ] openshift-storage                                 	db-noobaa-db-pg-0                                 	ocs-storagecluster-ceph-rbd
- [ ] rhods-notebooks                                   	jupyterhub-nb-mdargatz-40redhat-2ecom-pvc         	ocs-storagecluster-cephfs
- [ ] road-classification                               	telemetry-training                                	ocs-storagecluster-cephfs

**Comment by rbo** [comment]
### Change chipset type from I440FX to q35 at `ocp4bastion`

* https://redhat-internal.slack.com/archives/C06L4KBR4RW/p1736261330853029


Let's try on `ocp4bastion`:

```bash
for NIC in /sys/class/net/* ; do IFNAME=$(basename ${NIC}); TYPE=$(cat ${NIC}/type); MAC=$(cat ${NIC}/address); if [ ${TYPE} -ne 772 ]; then printf "SUBSYSTEM==\"net\",ACTION==\"add\",ATTR{address}==\"${MAC}\",ATTR{type}==\"${TYPE}\",NAME=\"${IFNAME}\"\n" | tee -a /etc/udev/rules.d/70-persistent-net.rules ;fi; done
```

Output:
```
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="56:6f:39:db:00:ce",ATTR{type}=="1",NAME="ens2"
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="56:6f:39:db:00:d0",ATTR{type}=="1",NAME="ens5"
```

```bash
[root@ocp4bastion ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:39:db:00:ce brd ff:ff:ff:ff:ff:ff
    inet 10.32.105.44/20 brd 10.32.111.255 scope global noprefixroute ens2
       valid_lft forever preferred_lft forever
    inet6 2620:52:0:2060:546f:39ff:fedb:ce/64 scope global dynamic mngtmpaddr
       valid_lft 2591990sec preferred_lft 604790sec
    inet6 fe80::546f:39ff:fedb:ce/64 scope link
       valid_lft forever preferred_lft forever
3: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:39:db:00:d0 brd ff:ff:ff:ff:ff:ff
    inet 172.16.10.1/24 brd 172.16.10.255 scope global noprefixroute ens5
       valid_lft forever preferred_lft forever
    inet6 fe80::546f:39ff:fedb:d0/64 scope link
       valid_lft forever preferred_lft forever
```

=> Change chip set from I440FX to q35 & Reboot

✅ All good, device names are still the same.

**Comment by rbo** [comment]
### Change chipset type from I440FX to q35 at `ocp4compute-0`

Let's try something hideous and definitely unsupported. 

Created `/etc/udev/rules.d/70-persistent-net.rules` by hand. 
```bash
[root@compute-0 ~]# cat /etc/udev/rules.d/70-persistent-net.rules
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="42:42:42:42:04:20",ATTR{type}=="1",NAME="ens2"
[root@compute-0 ~]#
```

👨🏽‍💻  Let's drain the node, change chipset and reboot. 
✅ All good, device names are still the same.

**Comment by rbo** [comment]
Storage clean-up is done. 

Let's uninstall ODF https://access.redhat.com/articles/6525111

**Comment by rbo** [comment]
✅ Graceful shutdown of the cluster done - https://examples.openshift.pub/cluster-lifecycle/shutdown/
✅ Removed Host devices (GPU's & NVME's)

**Comment by rbo** [comment]
![image](https://github.com/user-attachments/assets/52d6b176-e9e7-4ec4-815b-de08f318dad9)

**Comment by rbo** [comment]
Forgot some VLAN settings at the cisco blade center. VLAN 1004 was not available a the blade center.

```bash
oc get nodes
NAME                                           STATUS   ROLES    AGE      VERSION
compute-0.ocp4.stormshift.coe.muc.redhat.com   Ready    worker   422d     v1.30.6
compute-1.ocp4.stormshift.coe.muc.redhat.com   Ready    worker   4y360d   v1.30.6
compute-2.ocp4.stormshift.coe.muc.redhat.com   Ready    worker   4y94d    v1.30.6
control-0.ocp4.stormshift.coe.muc.redhat.com   Ready    master   4y360d   v1.30.6
control-1.ocp4.stormshift.coe.muc.redhat.com   Ready    master   4y360d   v1.30.6
control-2.ocp4.stormshift.coe.muc.redhat.com   Ready    master   4y360d   v1.30.6
```

I changed the control-plane node to control-plane only. 

Let's give ocp4 some time to start everything..

**Comment by rbo** [comment]
DONE successful migrated!
