### ISSUE TITLE
migrate or move ocp5

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/automation#59]
ODF NVMes from storm2,5,6

## ToDo's

- [x] Install NetApp Trident at ocp5 => @rbo 
- [x] coe-netapp-san / coe-netapp-nas as default storage class?
- [ ] Migrate storage from ODF to NetApp
- [ ] Uninstall ODF
- [ ] Move VM's to ISAR Cluster

**Comment by rbo** [comment]
Is there any hard requirement for ODF on that cluster?

**Comment by stefan-bergstein** [comment]
The primary use case for ocp5 with bare metal nodes and ODF is self-education for SAs and customer demos for OCP-virt.

**Comment by rbo** [comment]
What's with NetApp Trident NFS (file), iSCSI (RWX for Life Migration)? 

Don't get me wrong, I would not steal ODF. Just want to open for all the options.

**Comment by rbo** [comment]
Added `cluster-configuration` argocd application to rollout NetApp Trident via ArgoCD

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-12-08T15:40:00Z"
  generation: 2
  name: cluster-configuration
  namespace: openshift-gitops
  resourceVersion: "3231085294"
  uid: 116d2cb8-a02a-421b-850f-1a502cd402c0
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: configuration/overlays/stormshift-ocp5
    repoURL: https://github.com/stormshift/clusters.git
    targetRevision: HEAD

```

**Comment by rbo** [comment]
Installed external secrets operator, start failed with: `SignatureValidationFailed`
https://console-openshift-console.apps.ocp5.stormshift.coe.muc.redhat.com/k8s/ns/openshift-operators/deployments/external-secrets-operator-controller-manager/pods

**Comment by rbo** [comment]
I can not deploy netapp trident as well, because of:
```
Failed to pull image "quay.coe.muc.redhat.com/netapp/trident:24.10.0": SignatureValidationFailed: copying system image from manifest list: Source image rejected: Running image docker://quay.coe.muc.redhat.com/netapp/trident:24.10.0 is rejected by policy.
```

**Comment by rbo** [comment]
```
$ oc get images.config cluster -o yaml
...
spec:
  registrySources:
    allowedRegistries:
    - docker.io
    - registry.gitlab.com
    - quay.io
    - registry.redhat.io
    - image-registry.openshift-image-registry.svc:5000
    - '*.container.someone.com'
    - registry.connect.redhat.com
    - ghcr.io/bakito/sealed-secrets-web:v3.1.1
    - ghcr.io/external-secrets/                                     <= Added
    - gcr.io
    - registry.access.redhat.com
    - container-registry.oracle.com
    - quay.coe.muc.redhat.com                                     <= Added
```

**Comment by rbo** [comment]
Added new Red Hat Root ca to gobal trust bundle:
```
oc edit cm -n openshift-config user-ca-bundle
```

**Comment by rbo** [comment]
Final allowed allowedRegistries
```
  registrySources:
    allowedRegistries:
    - docker.io
    - registry.gitlab.com
    - quay.io
    - registry.redhat.io
    - image-registry.openshift-image-registry.svc:5000
    - '*.container.someone.com'
    - registry.connect.redhat.com
    - ghcr.io
    - gcr.io
    - registry.access.redhat.com
    - container-registry.oracle.com
    - quay.coe.muc.redhat.com
    - registry.k8s.io
```
